# Basic Information 
title: Yaolei Qi
position: Ph.D. Student
affiliation: Southeast University
affiliation_link: 
affiliation_logo: 
email: Yaolei710 (at) foxmail.com

# Search Engine Optimization (SEO)
keywords: yaolei qi
canonical: 
description: Yaolei Qi is a Ph.D. student at Southeast University. His research lies in medical image processing, network design, tubular structure analysis and image segmentation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=43lNKkcAAAAJ&hl=zh-CN
cv_link: https://github.com/YaoleiQi/
github_link: https://github.com/YaoleiQi/
linkedin: https://github.com/YaoleiQi/
twitter: https://github.com/YaoleiQi/

# Images 
avatar: ./assets/img/avatar.png
favicon: ./html_source_file/assets/img/favicon.png
favicon_dark: ./html_source_file/assets/img/favicon-dark.png

# Footnotes
footnote: Thanks yaoyao-liu for his very exquisite template, feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
